version: '3'

services:

  #React Nextjs Node Service

  node:

    image: webskittersdocker/node14:latest

    container_name: bluetees-node14

    restart: unless-stopped

    working_dir: /home/wtsadmin/myapp

    environment:

      - NODE_ENV=production

    
    volumes:

      - ./:/home/wtsadmin/myapp

    ports:

      - "1608:1608"
    command: >
      sh -c "npm install -f &&
             npm start"


#Docker Networks

networks:
  default:
    external:
      name: webskitters
